### ISSUE TITLE
Changing options has no effect

### ISSUE THREAD

**Issue by DerKobe** [wangzuo/react-medium-editor#30]
First I pass options `{disableEditing: true, toolbar: false}` but when I change them (triggered by a props-change) the editor is still read-only.

My render function looks like this:

```
  render() {
    let options = {}
    if (this.props.user.firstTime) {
      options = {disableEditing: true, toolbar: false}
    }

    return(
      <div className="content">
        <Editor
          text={this.state.text}
          onChange={this.handleChange}
          options={options}
        />
      </div>
    )
  }
```

**Comment by shark0der** [comment]
Had the same issue. This is due to the fact that `medium-editor` which this component is wrapping is not a react component itself, it's written in plain JS. The options are passed to it only the first time when it's rendered and it initializes `MediumEditor`, therefore changing the options afterwards has no effect.

Your best options are either to force a re-render or since you would like to just disable editing, you could render another component instead:

``` javascript
    return(
      <div className="content">
        {editing
        ? <Editor
          text={this.state.text}
          onChange={this.handleChange}
          options={options}
        />
        : <p>{this.state.text}</p>
        }
      </div>
    )
```

**Comment by DerKobe** [comment]
Yeah, I came to the same conclusion and it works fine so far :-) So I guess this is nothing that can be fixed in the "wrapper".
